# Generated by Django 4.1.1 on 2022-10-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incrown_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha', models.CharField(max_length=50)),
                ('hora', models.CharField(max_length=50)),
                ('esPublico', models.BooleanField(null=True)),
                ('aforo', models.PositiveIntegerField(null=True)),
                ('categoria', models.CharField(max_length=50)),
                ('organizador', models.CharField(max_length=200)),
                ('participantes', models.ManyToManyField(related_name='usuario_apuntado_a', to='incrown_app.usuario')),
            ],
        ),
    ]
