# Generated by Django 4.1.1 on 2022-10-26 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incrown_app', '0002_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='incrown_app.usuario')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='incrown_app.evento')),
            ],
        ),
    ]
